version: '3.8'

networks:
  emarket:

x-logging:
  &default-logging
  options:
    max-size: '20m'
    max-file: '3'
  driver: json-file  

services:
  redis:
    image: redislabs/redistimeseries:1.8.5
    container_name: emarket-redis
    logging: *default-logging
    restart: unless-stopped
    networks:
      - emarket
    ports:
      - "6379:6379"
    volumes:
      - ./.data/redis:/data:rw"
      
  grafana:
    image: grafana/grafana:9.3.6
    container_name: emarket-grafana
    restart: unless-stopped
    logging: *default-logging
    networks:
      - emarket
    ports:
      - "3001:3000"
    volumes:
      - ./.data/grafana:/var/lib/grafana:rw
      - ./cfg/grafana/config.ini:/etc/grafana/config.ini:ro
      - ./cfg/grafana/datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml:ro
      - ./cfg/grafana/dashboards.yaml:/etc/grafana/provisioning/dashboards/dashboards.yaml:ro
      - ./cfg/grafana/dashboards:/var/lib/grafana-dashboards:ro
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GF_ADMIN_PASS}
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_ENABLE_GZIP=true
      - GF_INSTALL_PLUGINS=redis-datasource
      - GF_FEATURE_TOGGLES_ENABLE=publicDashboards

  importer:
    image: airenas/emarket-importer:${IMPORTER_VERSION}
    container_name: emarket-importer
    restart: unless-stopped
    logging: *default-logging
    networks:
      - emarket
    environment:
      - RUST_LOG=INFO
      - KEY=${KEY}
      - REDIS_URL=redis://redis:6379
